package:
  name: pipy
  version: 0.1.0

source:
  path: "./src"
  path: .

build:
  noarch: python
  number: 0
  # Even though you're using pip here, it's just to install the directory contents directly without a setup.py. The actual build  and dependencies are handled by conda-build.
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python>=3.9
    - numpy=1.26.*
  channels:
    - conda-forge
    - defaults


test:
  requires:
    - conda-forge::pytest=8.2.*
  source_files:
    - ./src/pipy/*
    - ./tests/*
  imports:
    - pipy
    - pipy.calculators
  commands:
    - pytest


about:
  home: "http://example.com"
  license: "MIT"
  license_file: "LICENSE"
  summary: "A test package to calculate Pi using various methods."
  description: "This package provides various methods to calculate the value of Pi. It serves as an educational tool to understand conda package creation."
  doc_url: "http://example.com/documentation"
  dev_url: "http://example.com/source"

extra:
  recipe-maintainers:
    - julian.grimm@fh-wels.at
