package:
  name: pipy
  version: 0.1.0

source:
  path: .

build:
  noarch: python
  number: 0


requirements:
  host:
    - python >=3.9
    - {{ pin_compatible('numpy') }}
  run:
    - python>=3.9
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - ./pipy/*
    - ./tests/*
  imports:
    - pipy
    - pipy.calculators


about:
  home: "http://example.com"
  license: "MIT"
  license_file: "LICENSE"
  summary: "A test package to calculate Pi using various methods."
  description: "This package provides various methods to calculate the value of Pi. It serves as an educational tool to understand conda package creation."
  doc_url: "http://example.com/documentation"
  dev_url: "http://example.com/source"

extra:
  recipe-maintainers:
    - julian.grimm@fh-wels.at
