name: Generate Diagrams

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.key }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        pip install pylint==3.2.*

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2


  generate-diagrams:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create directory for diagrams
      run: mkdir -p ./docs/pyreverse

    - name: Generate diagrams with Pyreverse
      run: |
        pyreverse -p pipy -o png -d ./docs/pyreverse --source-roots ./src ./src/pipy

    - name: Upload diagrams
      uses: actions/upload-artifact@v4
      with:
        name: diagrams
        path: ./docs/pyreverse/*.png


  process-results:
    needs: generate-diagrams
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download diagrams
      uses: actions/download-artifact@v3
      with:
        name: diagrams
        path: ./docs/pyreverse
        
    - name: Commit and Push Diagrams back to the repository
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add ./docs/pyreverse/*.png
        git commit -m "Update diagrams" || echo "No changes to commit"
        git push
